development:
  adapter: postgresql
  encoding: unicode
  database: blogging_app
  pool: 5
  username: mybloggingapp
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: blogging_app_test
  pool: 5
  username: mybloggingapp
  password: postgres